name: Python CI
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip install poetry
      - name: Run linter and pytest
        run: poetry run flake8 brain_games
        
