name: Python CI
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - Install dependencies
        run: pip install poetry
      
      - name: Run linter and pytest
        run: make lint
        
